name: AI Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *" # Weekly scan

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Cache Hugging Face models for faster repeated runs
      - name: Cache Hugging Face models
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface/transformers
          key: hf-models-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Run Static Code Analysis
        run: |
          python scripts/static_analysis.py

      - name: Run Dependency Scan
        run: |
          python scripts/dependency_scan.py

      - name: Merge Reports
        run: |
          python scripts/merge_reports.py

      - name: Generate AI Summary (Hugging Face)
        run: |
          python scripts/ai_summarizer.py

      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-reports
          path: reports/
